services:
  - type: web
    name: weather-intelligence-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: NODE_ENV
        value: 'production'
      - key: PORT
        value: '9000'
      # - key: REDIS_URL
      #   fromService: redis
      #   name: weather-intelligence-redis
      #   property: connectionString

  # - type: redis
  #  name: weather-intelligence-redis
  #  plan: starter
  #  maxmemoryPolicy: allkeys-lru
